name: Pre Release

on:
  workflow_dispatch:
    inputs:
      pre_id:
        description: "Prerelease identifier"
        required: true
        type: choice
        default: "alpha"
        options:
          - alpha
          - beta
          - rc
      skip_tag:
        description: "Skip adding git tag to the version bump commit"
        required: false
        type: boolean
        default: false
      skip_commit:
        description: "Skip committing the version bump"
        required: false
        type: boolean
        default: false
      skip_push:
        description: "Skip pushing any commits or tags created after the version bump"
        required: false
        type: boolean
        default: false

env:
  HUSKY: 0

permissions:
  contents: write
  id-token: write

jobs:
  pre-release:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: https://registry.npmjs.org/

      - id: bump_version
        name: Bump Version and Tag Pre-Release
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default: "prerelease"
          version-type: "prerelease"
          preid: ${{ inputs.pre_id }}
          tag-prefix: "v"
          target-branch: ${{ github.ref_name }}
          commit-message: "chore: bump version to `{{version}}`"
          bump-policy: "all"
          skip-tag: ${{ inputs.skip_tag }}
          skip-commit: ${{ inputs.skip_commit }}
          skip-push: ${{ inputs.skip_push }}

      - name: Publish Pre-Release to NPM registry
        run: npm publish --tag prerelease --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump_version.outputs.newTag }}
          prerelease: true
          draft: false
          generate_release_notes: true
