name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version type to bump"
        required: true
        type: choice
        default: "patch"
        options:
          - patch
          - minor
          - major
      skip_tag:
        description: "Avoid to add a TAG to the version update commit"
        required: false
        type: boolean
        default: false
      skip_commit:
        description: "Avoid to add a commit after the version is bumped"
        required: false
        type: boolean
        default: false
      skip_push:
        description: "If true, skip pushing any commits or tags created after the version bump"
        required: false
        type: boolean
        default: false

env:
  HUSKY: 0

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: https://registry.npmjs.org/

      - name: Publish latest version to NPM registry
        run: npm publish --tag latest --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - id: bump_version
        name: Bump Version and Tag Release
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default: ${{ inputs.version_type }}
          version-type: ${{ inputs.version_type }}
          tag-prefix: "v"
          target-branch: ${{ github.ref_name }}
          commit-message: "chore: bump version to `{{version}}`"
          bump-policy: "all"
          skip-tag: ${{ inputs.skip_tag }}
          skip-commit: ${{ inputs.skip_commit }}
          skip-push: ${{ inputs.skip_push }}

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          prerelease: false
          draft: false
          generate_release_notes: true
